defaultPortal: stephenk
portals:
  - name: stephenk
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLDjlNWILxIEAA0ABBj36pIBINGnogUo7ukMMhkAUKSbU-E8Zqc0_zFJez73LLdTb7LvvTVEOigAAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYAAAAAAAAAAAAABgQhkAUKSbU6yatApHcIm9Yzpk8IPg7a0xHQUrSgNuYTE
        expiresAt: '2021-03-31T23:36:25.270Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
