defaultPortal: lone-fir
portals:
  - name: lone-fir
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKODv7z_LhIEAA0ABBj36pIBINGnogUo7ukMMhkAJHbtbzbKnbVxg5qR9d2luuw5xoZJLbfIOh0AAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYEIZACR27W-3A98yX4LOIc5cWYroeYVQ3LG5LA
        expiresAt: '2021-03-03T10:08:49.577Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
