defaultPortal: lone-fir
portals:
  - name: lone-fir
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COKHw5T_LhIEAA0ABBj36pIBINGnogUo7ukMMhkAhrGTsgIFbYqwBCbXQSXYqB4_NC4ZZJhKOh0AAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYEIZAIaxk7L5DqxWti71fO5937bsYeY-pnAUbg
        expiresAt: '2021-03-02T10:51:49.608Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
