defaultPortal: lone-fir
portals:
  - name: lone-fir
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CP7MnPT6LhIEAA0ABBj36pIBINGnogUo7ukMMhkAJs-TvAtFSHyloNo0bjunPwgaEyaJMiyIOh0AAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYEIZACbPk7w451N6EUizvl3ya2MH1WRnVNI7cg
        expiresAt: '2021-02-17T05:47:08.807Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
