defaultPortal: lone-fir
portals:
  - name: lone-fir
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLfviIf_LhIEAA0ABBj36pIBINGnogUo7ukMMhkAi5mDCFj-8SIDEbDDZaAwUg5snLRUD5LOOh0AAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYEIZAIuZgwgn1yTpp_Bwldordnb2dyNElrUp4w
        expiresAt: '2021-03-02T03:01:33.245Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
