defaultPortal: lone-fir
portals:
  - name: lone-fir
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI-cgZH7LhIEAA0ABBj36pIBINGnogUo7ukMMhkAQjyYqvc_LYnnguJz3oiH4WQyJD8qMAQnOh0AAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYEIZAEI8mKpsyZvlST4OHrYhI0nAl5FgHPeMKQ
        expiresAt: '2021-02-17T22:33:17.588Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
