defaultPortal: lone-fir
portals:
  - name: lone-fir
    portalId: 2405751
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJeMzf3-LhIEAA0ABBj36pIBINGnogUo7ukMMhkAqKTOEtdrJW0fqk6-y-144mfMCDwDY4x4Oh0AAARBAAAAeAAAAAAAAAAAgAAAAAAAAAQAAMAHYEIZAKikzhK4kWHvzALXg00e6FbI9rVIgeh2kA
        expiresAt: '2021-03-01T21:30:39.518Z'
    personalAccessKey: >-
      CiRlODc5MTQxYS02YTZiLTQzZWMtOWVmNy1lZmRkMDVjMTg3ZjMQ9-qSARjRp6IFKhkABeaRgq5KzCxzRL9t-ZeQWwW_eDtqoIYc
